name: Build release
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-2025
    permissions: write-all
    steps:
      - name: Put current date into a variable
        run: |
          $NOW=& Get-Date -format yyyy-MM-dd-HH-mm-ss
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Create Executable
        id: pyinstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'src/main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SplitFacturas'
          options: --onefile, --name "SplitFacturas", --windowed, 

      - name: Zip output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r SplitFacturas.zip SplitFacturas.exe
          working-directory: ${{ steps.pyinstaller.outputs.executable_path }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ steps.pyinstaller.outputs.executable_path }}/SplitFacturas.zip'
          tag: ${{env.NOW}}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This is the release body
        