name: Build release
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-2025
    permissions: write-all
    env:
      ARTIFACT_NAME: SplitFacturas
    steps:
      - name: Put current date into a variable
        run: |
          $NOW=& Get-Date -format yyyyMMddHHmmss
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install PyInstaller
        run: python -m pip install PyInstaller

      - name: Run PyInstaller
        run: python -m PyInstaller --name ${{env.ARTIFACT_NAME}} --windowed --onefile src/main.py

      - name: Zip output
        run: Compress-Archive -Path ${{env.ARTIFACT_NAME}}.exe -Destination ${{env.ARTIFACT_NAME}}.zip
        working-directory: './dist'

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: './dist/${{env.ARTIFACT_NAME}}.zip'
          tag: ${{env.NOW}}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: '${{env.ARTIFACT_NAME}} new release ${{env.NOW}}'
        