name: Build release
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'src/main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'SplitFacturas'
          options: --onefile, --name "SplitFacturas", --windowed, 